using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DataModels
{
    public class G5_memberModel
    {
        public int mb_no { get; set; } // int (11) NOT NULL AUTO_INCREMENT,
        public string mb_id { get; set; } // varchar(20) NOT NULL DEFAULT '',
        public string mb_sn { get; set; } // varchar(255) NOT NULL DEFAULT '',
        public string mb_password { get; set; } // varchar(255) NOT NULL DEFAULT '',
        public string mb_name { get; set; } // varchar(255) NOT NULL DEFAULT '',
        public string mb_nick { get; set; } // varchar(255) NOT NULL DEFAULT '',
        public DateTime mb_nick_date { get; set; } // date NOT NULL DEFAULT '0000-00-00',
        public string mb_email { get; set; } // varchar(255) NOT NULL DEFAULT '',
        public string mb_homepage { get; set; } // varchar(255) NOT NULL DEFAULT '',
        public int mb_level { get; set; } // tinyint(4) NOT NULL DEFAULT '0',
        public string mb_sex { get; set; } // char (1) NOT NULL DEFAULT '',
        public string mb_birth { get; set; } // varchar(255) NOT NULL DEFAULT '',
        public string mb_tel { get; set; } // varchar(255) NOT NULL DEFAULT '',
        public string mb_hp { get; set; } // varchar(255) NOT NULL DEFAULT '',
        public string mb_certify { get; set; } // varchar(20) NOT NULL DEFAULT '',
        public int mb_adult { get; set; } // tinyint(4) NOT NULL DEFAULT '0',
        public string mb_dupinfo { get; set; } // varchar(255) NOT NULL DEFAULT '',
        public string mb_zip1 { get; set; } // char (3) NOT NULL DEFAULT '',
        public string mb_zip2 { get; set; } // char (3) NOT NULL DEFAULT '',
        public string mb_addr1 { get; set; } // varchar(255) NOT NULL DEFAULT '',
        public string mb_addr2 { get; set; } // varchar(255) NOT NULL DEFAULT '',
        public string mb_addr3 { get; set; } // varchar(255) NOT NULL DEFAULT '',
        public string mb_addr_jibeon { get; set; } // varchar(255) NOT NULL DEFAULT '',
        public string mb_signature { get; set; } // text NOT NULL,
        public string mb_recommend { get; set; } // varchar(255) NOT NULL DEFAULT '',
        public int mb_point { get; set; } // int (11) NOT NULL DEFAULT '0',
        public DateTime mb_today_login { get; set; } // datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
        public string mb_login_ip { get; set; } // varchar(255) NOT NULL DEFAULT '',
        public DateTime mb_datetime { get; set; } // datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
        public string mb_ip { get; set; } // varchar(255) NOT NULL DEFAULT '',
        public string mb_leave_date { get; set; } // varchar(8) NOT NULL DEFAULT '',
        public string mb_intercept_date { get; set; } // varchar(8) NOT NULL DEFAULT '',
        public DateTime mb_email_certify { get; set; } // datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
        public string mb_email_certify2 { get; set; } // varchar(255) NOT NULL DEFAULT '',
        public string mb_memo { get; set; } // text NOT NULL,
        public string mb_lost_certify { get; set; } // varchar(255) NOT NULL,
        public int mb_mailling { get; set; } // tinyint(4) NOT NULL DEFAULT '0',
        public int mb_sms { get; set; } // tinyint(4) NOT NULL DEFAULT '0',
        public int mb_open { get; set; } // tinyint(4) NOT NULL DEFAULT '0',
        public DateTime mb_open_date { get; set; } // date NOT NULL DEFAULT '0000-00-00',
        public string mb_profile { get; set; } // text NOT NULL,
        public string mb_memo_call { get; set; } // varchar(255) NOT NULL DEFAULT '',
        public string mb_1 { get; set; } // varchar(255) NOT NULL DEFAULT '',
        public string mb_2  { get; set; } // varchar(255) NOT NULL DEFAULT '',
        public string mb_3  { get; set; } // varchar(255) NOT NULL DEFAULT '',
        public string mb_4  { get; set; } // varchar(255) NOT NULL DEFAULT '',
        public string mb_5  { get; set; } // varchar(255) NOT NULL DEFAULT '',
        public string mb_6  { get; set; } // varchar(255) NOT NULL DEFAULT '',
        public string mb_7  { get; set; } // varchar(255) NOT NULL DEFAULT '',
        public string mb_8  { get; set; } // varchar(255) NOT NULL DEFAULT '',
        public string mb_9 { get; set; } // varchar(255) NOT NULL DEFAULT '',
        public string mb_10 { get; set; } // varchar(255) NOT NULL DEFAULT '',
        public int as_msg { get; set; } // tinyint(4) NOT NULL DEFAULT '0',
        public int as_photo { get; set; } // tinyint(4) NOT NULL DEFAULT '0',
        public int as_partner { get; set; } // tinyint(4) NOT NULL DEFAULT '0',
        public int as_marketer { get; set; } // tinyint(4) NOT NULL DEFAULT '0',
        public int as_exp { get; set; } // int (11) NOT NULL DEFAULT '0',
        public int as_level { get; set; } // int (11) NOT NULL DEFAULT '1',
        public int as_like { get; set; } // int (11) NOT NULL DEFAULT '0',
        public int as_liked { get; set; } // int (11) NOT NULL DEFAULT '0',
        public int as_follow { get; set; } // int (11) NOT NULL DEFAULT '0',
        public int as_followed { get; set; } // int (11) NOT NULL DEFAULT '0',
        public int as_response { get; set; } // int (11) NOT NULL DEFAULT '0',
        public int as_memo { get; set; } // int (11) NOT NULL DEFAULT '0',
        public int as_coupon { get; set; } // int (11) NOT NULL DEFAULT '0',
        public int as_join { get; set; } // int (11) NOT NULL DEFAULT '0',
        public int as_date { get; set; } // int (11) NOT NULL DEFAULT '0',
    }
}
